<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-OB1OE1J" failures="5" tests="27" name="Smoke Testcases(failed)" time="1390.396" errors="0" timestamp="2021-07-24T07:01:35 IST">
  <testcase classname="com.nitara.base.GenericBase" name="@BeforeMethod getUserAuthenticationToken" time="48.333">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.nitara.base.GenericBase.getUserAuthenticationToken(GenericBase.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'D', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 36 more
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod getUserAuthenticationToken -->
  <testcase classname="com.nitara.base.GenericBase" name="@BeforeMethod getUserAuthenticationToken" time="42.691">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.nitara.base.GenericBase.getUserAuthenticationToken(GenericBase.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'D', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 36 more
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod getUserAuthenticationToken -->
  <testcase classname="com.nitara.base.GenericBase" name="@BeforeMethod getUserAuthenticationToken" time="37.575">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.nitara.base.GenericBase.getUserAuthenticationToken(GenericBase.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'D', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 36 more
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod getUserAuthenticationToken -->
  <testcase classname="com.nitara.base.GenericBase" name="@BeforeMethod getUserAuthenticationToken" time="46.377">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.nitara.base.GenericBase.getUserAuthenticationToken(GenericBase.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'D', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 36 more
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod getUserAuthenticationToken -->
  <testcase classname="com.nitara.base.GenericBase" name="@BeforeMethod getUserAuthenticationToken" time="54.371">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.nitara.base.GenericBase.getUserAuthenticationToken(GenericBase.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'D', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 36 more
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod getUserAuthenticationToken -->
  <testcase classname="com.nitara.base.GenericBase" name="@BeforeMethod getUserAuthenticationToken" time="61.747">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.nitara.base.GenericBase.getUserAuthenticationToken(GenericBase.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'D', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 35 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod getUserAuthenticationToken -->
  <testcase classname="com.nitara.base.GenericBase" name="@BeforeMethod getUserAuthenticationToken" time="29.895">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.nitara.base.GenericBase.getUserAuthenticationToken(GenericBase.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'D', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 35 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod getUserAuthenticationToken -->
  <testcase classname="com.nitara.base.GenericBase" name="@BeforeMethod getUserAuthenticationToken" time="29.685">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.nitara.base.GenericBase.getUserAuthenticationToken(GenericBase.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'D', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 35 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod getUserAuthenticationToken -->
  <testcase classname="com.nitara.base.GenericBase" name="@BeforeMethod getUserAuthenticationToken" time="45.69">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.nitara.base.GenericBase.getUserAuthenticationToken(GenericBase.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'D', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 35 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod getUserAuthenticationToken -->
  <testcase classname="com.nitara.base.GenericBase" name="@BeforeMethod getUserAuthenticationToken" time="32.229">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.nitara.base.GenericBase.getUserAuthenticationToken(GenericBase.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'D', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 35 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod getUserAuthenticationToken -->
  <testcase classname="com.nitara.base.GenericBase" name="@BeforeMethod getUserAuthenticationToken" time="42.803">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.nitara.base.GenericBase.getUserAuthenticationToken(GenericBase.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'D', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 35 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod getUserAuthenticationToken -->
  <testcase classname="com.nitara.base.GenericBase" name="@BeforeMethod getUserAuthenticationToken" time="45.768">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:930)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:895)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:975)
at io.restassured.path.json.JsonPath.get(JsonPath.java:201)
at com.nitara.base.GenericBase.getUserAuthenticationToken(GenericBase.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading 'D', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:83)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:893)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:928)
... 35 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod getUserAuthenticationToken -->
  <testcase classname="com.nitara.PDManagement.DeletePD" name="deletePD" time="20.123"/>
  <testcase classname="com.nitara.UserPreferenceManagement.GetUserBreedingPreferences" name="getUserBreedingPreferences" time="2.656"/>
  <testcase classname="com.nitara.FollowUp.AddFollowUp" name="AddFollowUpDetails" time="4.905">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at com.nitara.FollowUp.AddFollowUp.AddFollowUpDetails(AddFollowUp.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- AddFollowUpDetails -->
  <testcase classname="com.nitara.KYCManagement.RejectKYCDetails" name="rejectKYCDetails" time="34.084">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at com.nitara.KYCManagement.RejectKYCDetails.rejectKYCDetails(RejectKYCDetails.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- rejectKYCDetails -->
  <testcase classname="com.nitara.InseminationManagement.UpdateInsemination" name="updateInsemination" time="0.0">
    <skipped/>
  </testcase> <!-- updateInsemination -->
  <testcase classname="com.nitara.MasterData.GetDewormerMasterData" name="GetDewormerMasterDataInEnglish" time="0.602"/>
  <testcase classname="com.nitara.FarmManagement.GetFarmMetadata" name="getFarmMetadata" time="30.001"/>
  <testcase classname="com.nitara.FollowUp.DeleteFollowUp" name="deleteFollowUp" time="0.0">
    <skipped/>
  </testcase> <!-- deleteFollowUp -->
  <testcase classname="com.nitara.MilkingManagement.AddFarmMilking" name="addUserFarmMilking" time="0.0">
    <skipped/>
  </testcase> <!-- addUserFarmMilking -->
  <testcase classname="com.nitara.PDManagement.UpdatePD" name="updatePD" time="5.006">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at com.nitara.PDManagement.UpdatePD.updatePD(UpdatePD.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- updatePD -->
  <testcase classname="com.nitara.CattleManagement.UpdateBcs" name="updateBcs" time="14.438"/>
  <testcase classname="com.nitara.CattleManagement.UpdateTreatment" name="updateTreatment" time="0.0">
    <skipped/>
  </testcase> <!-- updateTreatment -->
  <testcase classname="com.nitara.MasterData.GetCattleTypeMaster" name="GetCattleTypeMasterInEnglish" time="0.294"/>
  <testcase classname="com.nitara.FarmManagement.ViewRevenue" name="viewRevenue" time="3.782"/>
  <testcase classname="com.nitara.UserPreferenceManagement.SetUserBreedingPreferences" name="SetBreedingPreferences" time="0.0">
    <skipped/>
  </testcase> <!-- SetBreedingPreferences -->
  <testcase classname="com.nitara.KYCManagement.SubmitKYCDetails" name="submitKYCDetails" time="32.348">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at com.nitara.KYCManagement.SubmitKYCDetails.submitKYCDetails(SubmitKYCDetails.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- submitKYCDetails -->
  <testcase classname="com.nitara.UserPreferenceManagement.SetUserHealthPreferences" name="SetHealthPreferences" time="0.0">
    <skipped/>
  </testcase> <!-- SetHealthPreferences -->
  <testcase classname="com.nitara.PDManagement.AddPD" name="addPD" time="0.0">
    <skipped/>
  </testcase> <!-- addPD -->
  <testcase classname="com.nitara.CattleManagement.DeleteBcs" name="deleteBcs" time="6.445"/>
  <testcase classname="com.nitara.AccountManagement.ViewFarmerHomePage" name="viewFarmerHomePage" time="70.349"/>
  <testcase classname="com.nitara.FollowUp.UpdateFollowUp" name="UpdateFollowUpDetails" time="0.0">
    <skipped/>
  </testcase> <!-- UpdateFollowUpDetails -->
  <testcase classname="com.nitara.DryPeriodManagement.UpdateDryPeriod" name="addDryPeriod" time="0.0">
    <skipped/>
  </testcase> <!-- addDryPeriod -->
  <testcase classname="com.nitara.DiseasePredictor.GetSymptoms" name="GetSymptoms" time="0.0">
    <skipped/>
  </testcase> <!-- GetSymptoms -->
  <testcase classname="com.nitara.MasterData.GetSemenBrandMasterData" name="GetSemenBrandMasterDataInEnglish" time="0.174"/>
  <testcase classname="com.nitara.CalvingManagement.UpdateCalving" name="updateCalving" time="31.529">
    <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at com.nitara.CalvingManagement.UpdateCalving.updateCalving(UpdateCalving.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- updateCalving -->
  <testcase classname="com.nitara.CattleManagement.AddBcs" name="addBcsDetails" time="0.0">
    <skipped/>
  </testcase> <!-- addBcsDetails -->
  <testcase classname="com.nitara.HeatManagement.DeleteHeat" name="deleteHeat" time="0.0">
    <skipped/>
  </testcase> <!-- deleteHeat -->
</testsuite> <!-- Smoke Testcases(failed) -->
